# Generated by Django 6.0.7 on 2026-07-26 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='description',
        ),
    ]
