# Generated by Django 6.0.7 on 2026-07-27 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0004_remove_task_description_todo_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='target_duration_seconds',
            field=models.IntegerField(default=1500),
        ),
    ]
